stages:
  prep_pipeline:
    cmd: uv run python src/app/prep_pipeline.py
    deps:
      - src/app/prep_pipeline.py

  extract:
    cmd: uv run python src/app/extract.py --input data/raw/documents --output
      data/processed/extracted
    deps:
      - data/raw/documents
      - src/app/extract.py
    outs:
      - data/processed/extracted
    params:
      - extract.batch_size
      - extract.source_handling
    frozen: true

  naiverag_chunk:
    cmd: uv run python src/app/naiverag/chunk.py --input data/processed/extracted --output data/processed/chunks
    deps:
      - src/app/naiverag/chunk.py
      - data/processed/extracted
    outs:
      - data/processed/chunks
    params:
      - chunk.chunk_size
      - chunk.overlap
      - chunk.split_by

  naiverag_embed:
    cmd: uv run python src/app/naiverag/embed.py --input data/processed/chunks --artifacts data/processed/extracted --database_url postgresql://postgres:postgres@127.0.0.1:54322/postgres
    deps:
      - src/app/naiverag/embed.py
      - data/processed/chunks
      - data/processed/extracted

  linearrag_load:
    cmd: uv run python src/app/linear_rag/load.py --input data/processed/chunks --artifacts data/processed/extracted --database_url postgresql://postgres:postgres@127.0.0.1:54322/postgres
    deps:
      - src/app/linear_rag/load.py
      - data/processed/chunks
      - data/processed/extracted
    params:
      - load.batch_size

  linearrag_index:
    cmd: uv run python src/app/linear_rag/index.py --database_url postgresql://postgres:postgres@127.0.0.1:54322/postgres
    deps:
      - src/app/linear_rag/index.py
    params:
      - index.batch_size
      - index.spacy_model

  generate_queries:
    cmd: uv run open-rag-eval generate-queries --config query_gen_config.yaml
    deps:
      - query_gen_config.yaml
      - data/processed/extracted
    outs:
      - data/eval/queries.csv
    params:
      - query_gen_config.yaml:
          - model.type
          - model.name
          - generation.n_questions
          - generation.questions_per_doc

  linearrag_generate_answers:
    cmd: >-
      OLLAMA_BASE_URL=http://127.0.0.1:11434/v1
      OLLAMA_MODEL=bge-m3:567m
      uv run python src/app/eval_open_rag.py
      --system linearrag
      --queries data/eval/queries.csv
      --output data/eval/linearrag/generated_answers.csv
      --database_url postgresql://postgres:postgres@127.0.0.1:54322/postgres
    deps:
      - src/app/eval_open_rag.py
      - src/app/linear_rag/retrieve.py
      - src/app/utils/params_helper.py
      - data/eval/queries.csv
    outs:
      - data/eval/linearrag/generated_answers.csv
    params:
      - eval.top_k
      - generation.max_tokens
      - retrieval.retrieval_top_k
      - index.spacy_model
      - index.embedding_provider

  linearrag_eval:
    cmd: >-
      uv run open-rag-eval eval
      --config configs/open_rag_eval_linearrag.yaml
    deps:
      - configs/open_rag_eval_linearrag.yaml
      - data/eval/queries.csv
      - data/eval/linearrag/generated_answers.csv
    outs:
      - data/eval/linearrag/results.csv
      - data/eval/linearrag/TRECEvaluator-metrics.png
    params:
      - configs/open_rag_eval_linearrag.yaml:
          - evaluator.0.model.type
          - evaluator.0.model.name
          - evaluator.0.options.k_values

  graphmert_corpus:
    cmd: uv run python src/app/graphmert/corpus.py
    deps:
      - src/app/graphmert/corpus.py
      - data/processed/chunks
    outs:
      - data/graphmert/corpus

  graphmert_embeddings:
    cmd: uv run python src/app/graphmert/embeddings.py
    deps:
      - src/app/graphmert/embeddings.py
      - data/graphmert/corpus/corpus.json
    outs:
      - data/graphmert/embeddings

  graphmert_build_graphs:
    cmd: uv run python src/app/graphmert/build_graphs.py
    deps:
      - src/app/graphmert/build_graphs.py
      - data/graphmert/embeddings/reduced_embeddings.npy
    outs:
      - data/graphmert/graphs

  graphmert_train_model:
    cmd: uv run python src/app/graphmert/train_model.py
    deps:
      - src/app/graphmert/train_model.py
      - data/graphmert/graphs/sentence_transformer_fixed10d_graphs.json
    outs:
      - data/graphmert/model

  graphmert_generate_answers:
    cmd: >-
      uv run python src/app/eval_open_rag.py
      --system graphmert
      --queries data/eval/queries.csv
      --output data/eval/graphmert/generated_answers.csv
    deps:
      - src/app/eval_open_rag.py
      - src/app/graphmert/corpus.py
      - src/app/graphmert/inference.py
      - src/app/graphmert/train_model.py
      - src/app/utils/params_helper.py
      - data/processed/chunks
      - data/eval/queries.csv
    outs:
      - data/eval/graphmert/generated_answers.csv
    params:
      - eval.top_k

  graphmert_eval:
    cmd: >-
      uv run open-rag-eval eval
      --config configs/open_rag_eval_graphmert.yaml
    deps:
      - configs/open_rag_eval_graphmert.yaml
      - data/eval/queries.csv
      - data/eval/graphmert/generated_answers.csv
    outs:
      - data/eval/graphmert/results.csv
      - data/eval/graphmert/TRECEvaluator-metrics.png
    params:
      - configs/open_rag_eval_graphmert.yaml:
          - evaluator.0.model.type
          - evaluator.0.model.name
          - evaluator.0.options.k_values

  naiverag_generate_answers:
    cmd: >-
      uv run python src/app/eval_open_rag.py
      --system naiverag
      --queries data/eval/queries.csv
      --output data/eval/naiverag/generated_answers.csv
    deps:
      - src/app/eval_open_rag.py
      - src/app/embedder.py
      - src/app/utils/params_helper.py
      - data/processed/chunks
      - data/eval/queries.csv
    outs:
      - data/eval/naiverag/generated_answers.csv
    params:
      - eval.top_k

  naiverag_eval:
    cmd: >-
      uv run open-rag-eval eval
      --config configs/open_rag_eval_naiverag.yaml
    deps:
      - configs/open_rag_eval_naiverag.yaml
      - data/eval/queries.csv
      - data/eval/naiverag/generated_answers.csv
    outs:
      - data/eval/naiverag/results.csv
      - data/eval/naiverag/TRECEvaluator-metrics.png
    params:
      - configs/open_rag_eval_naiverag.yaml:
          - evaluator.0.model.type
          - evaluator.0.model.name
          - evaluator.0.options.k_values
