stages:
  prep_pipeline:
    cmd: uv run python src/app/prep_pipeline.py
    deps:
      - src/app/prep_pipeline.py

  extract:
    cmd: uv run python src/app/extract.py --input data/raw/documents/2402.14887v4.pdf --output data/processed/extracted
    deps:
      - src/app/extract.py
      - data/raw/documents/2402.14887v4.pdf
    outs:
      - data/processed/extracted
    params:
      - extract.batch_size
      - extract.source_handling

  linearrag_chunk:
    cmd: uv run python src/app/linear_rag/chunk.py --input data/processed/extracted --output data/processed/linear_rag/chunks
    deps:
      - src/app/linear_rag/chunk.py
      - data/processed/extracted
    outs:
      - data/processed/linear_rag/chunks
    params:
      - chunk.chunk_size
      - chunk.overlap
      - chunk.split_by

  linearrag_load:
    cmd: uv run python src/app/linear_rag/load.py --input data/processed/linear_rag/chunks --artifacts data/processed/extracted --database_url postgresql://postgres:postgres@127.0.0.1:54322/postgres
    deps:
      - src/app/linear_rag/load.py
      - data/processed/linear_rag/chunks
      - data/processed/extracted
    params:
      - load.batch_size

  linearrag_index:
    cmd: uv run python src/app/linear_rag/index.py --database_url postgresql://postgres:postgres@127.0.0.1:54322/postgres
    deps:
      - src/app/linear_rag/index.py
    params:
      - index.batch_size
      - index.spacy_model

  naiverag_chunk:
    cmd: uv run python src/app/naiverag/chunk.py --input data/processed/extracted --output data/processed/chunks
    deps:
      - src/app/naiverag/chunk.py
      - data/processed/extracted
    outs:
      - data/processed/chunks
    params:
      - chunk.chunk_size
      - chunk.overlap
      - chunk.split_by

  naiverag_embed:
    cmd: uv run python src/app/naiverag/embed.py --input data/processed/chunks --artifacts data/processed/extracted --database_url postgresql://postgres:postgres@127.0.0.1:54322/postgres
    deps:
      - src/app/naiverag/embed.py
      - data/processed/chunks
      - data/processed/extracted

  graphmert_corpus:
    cmd: uv run python src/app/graphmert/corpus.py
    deps:
      - src/app/graphmert/corpus.py
      - data/processed/chunks
    outs:
      - data/graphmert/corpus

  graphmert_embeddings:
    cmd: uv run python src/app/graphmert/embeddings.py
    deps:
      - src/app/graphmert/embeddings.py
      - data/graphmert/corpus/corpus.json
    outs:
      - data/graphmert/embeddings

  graphmert_build_graphs:
    cmd: uv run python src/app/graphmert/build_graphs.py
    deps:
      - src/app/graphmert/build_graphs.py
      - data/graphmert/embeddings/reduced_embeddings.npy
    outs:
      - data/graphmert/graphs

  graphmert_train_model:
    cmd: uv run python src/app/graphmert/train_model.py
    deps:
      - src/app/graphmert/train_model.py
      - data/graphmert/graphs/sentence_transformer_fixed10d_graphs.json
    outs:
      - data/graphmert/model
