extract:
  batch_size: 1
  source_handling: "copy"

chunk:
  chunk_size: 500
  overlap: 100
  split_by: section

embed:
  model: "sentence-transformers/all-mpnet-base-v2"

graph:
  similarity_threshold: 0.75

eval:
  top_k: 5
